version: '3'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  api:
    build: .
    environment:
      - OPEN_WEATHER_MAP_KEY=477e687e73bd2028a642968cd1c2aead
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CACHE_TTL=300
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=60
      - NODE_ENV=production
    ports:
      - 3000:3000